version: "2"
services:
    web:
        image: georgitsenov/nodejs
        ports:
        - "80:3000"
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
        - "27017:27017"